Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - db/schema.rb
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
Style/SymbolProc:
  Exclude:
    - db/migrate/**/*
Style/MixinUsage:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/HashSyntax:
  Enabled: false
# Metrics/BlockLength:
#   Enabled: false
# Metrics/MethodLength:
#   Enabled: false
Metrics:
  Enabled: false
